### ISSUE TITLE
Build on linux ?

### ISSUE THREAD

**Issue by nmaster2042** [dmitryelj/SoapyICR8600#11]
I can't build on Linux (Kubuntu 21.10) and SoapySDR 0.8 built from source.

Here is what get

$ cmake ../
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: defaulting to release.
-- Performing Test HAS_STD_CXX11
-- Performing Test HAS_STD_CXX11 - Success
-- Found Git: /usr/bin/git (found version "2.32.0") 
-- Module icr8600Support configured with version: 0e0ebff
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nicolas/Applis/SDR/SoapyICR8600/build

$ make
canning dependencies of target icr8600Support
[ 16%] Building CXX object CMakeFiles/icr8600Support.dir/Registation.cpp.o
[ 33%] Building CXX object CMakeFiles/icr8600Support.dir/Settings.cpp.o
[ 50%] Building CXX object CMakeFiles/icr8600Support.dir/Streaming.cpp.o
[ 66%] Building CXX object CMakeFiles/icr8600Support.dir/WinUSBDevice.cpp.o
[ 83%] Building CXX object CMakeFiles/icr8600Support.dir/Version.cpp.o
[100%] Linking CXX shared module libicr8600Support.so
/usr/bin/ld : CMakeFiles/icr8600Support.dir/WinUSBDevice.cpp.o : dans la fonction « FindICR8600Device() » :
WinUSBDevice.cpp:(.text+0x2f2) : référence indéfinie vers « libusb_init »
/usr/bin/ld : WinUSBDevice.cpp:(.text+0x302) : référence indéfinie vers « libusb_get_device_list »
/usr/bin/ld : WinUSBDevice.cpp:(.text+0x32d) : référence indéfinie vers « libusb_get_device_descriptor »
/usr/bin/ld : WinUSBDevice.cpp:(.text+0x368) : référence indéfinie vers « libusb_free_device_list »
/usr/bin/ld : WinUSBDevice.cpp:(.text+0x36f) : référence indéfinie vers « libusb_exit »
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/icr8600Support.dir/build.make:164 : libicr8600Support.so] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:95 : CMakeFiles/icr8600Support.dir/all] Erreur 2
make: *** [Makefile:149 : all] Erreur 2

Any help ?

**Comment by dmitryelj** [comment]
It looks, you need a libusb-dev package:
_sudo apt-get install -y libusb-dev_

PS: I am not using ICR-8600 anymore, and I am not making any active support of this project.
