### ISSUE TITLE
GitHub Discussions for this project

### ISSUE THREAD

**Issue by robojay** [dmitryelj/SoapyICR8600#5]
Hi!

Can you turn on GitHub Discussions for this project?  It would be a good place to share tips, poke at issues (that might not be issues... or might be...), share which applications work with the driver, which don't, etc.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-or-disabling-github-discussions-for-a-repository#enabling-or-disabling-discussions-for-your-repository

Thanks,
Jay

**Comment by dmitryelj** [comment]
I enabled discussions, but I am not using 8600 more than a year, so cannot help too much in testing.

**Comment by robojay** [comment]
Thanks - even a better reason to add discussion :-)  Maybe a few people can be enticed to help test.
